name = "QuantexQASM"
uuid = "630b6936-434f-11ea-2df3-976e72da0e99"
authors = ["Lee J. O'Riordan <lee.oriordan@ichec.ie>"]
version = "0.1.0"

[deps]
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
